using System;

namespace SimpleCSharpProgram
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello, world!");
            Console.WriteLine("This is a simple C# program generated by Bing.");
            Console.WriteLine("Press any key to exit.");
            Console.ReadKey();
        }
    }
}
